Traceback (most recent call last):
  File "interactive_face_detection.py", line 588, in <module>
    sys.exit(main() or 0)
  File "interactive_face_detection.py", line 390, in main
    progressUpdate(infer_file, (sum(infer_times)/1000), framesCounter+1, 1718)
  File "/home/u26212/Reference-samples/iot-devcloud/demoTools/demoutils.py", line 250, in progressUpdate
    with  open(file_name, "w") as progress_file:
FileNotFoundError: [Errno 2] No such file or directory: 'results/ncs2_face/i_progress.txt'
